### ISSUE TITLE
[crash] unwrap panic while parsing invalid wasm module

### ISSUE THREAD

**Issue by pventuzelo** [rhysd/wain#28]
Hey, 

Found this bug while doing some testing. The module is invalid because the `version` is missing from the wasm header.

``` sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromSliceError(())', /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/wain-syntax-binary-0.1.2/src/parser.rs:241:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Download: [unwrap_panic_wain.zip](https://github.com/rhysd/wain/files/4763394/unwrap_panic_wain.zip)

``` sh
$ hexdump -C unwrap_panic_wain.wasm
00000000  00 61 73 6d                                       |.asm|
00000004
```

**Comment by rhysd** [comment]
Thank you for reporting this. I'll check it tonight.

**Comment by rhysd** [comment]
I could not reproduce this:

<img width="738" alt="スクリーンショット 2020-06-11 19 44 46" src="https://user-images.githubusercontent.com/823277/84376386-0881af80-ac1c-11ea-97dc-6c57c829ea86.png">

Would you check if the HEAD commit in your local is the latest?

And also please let me know the version of your Rust toolchain by showing output of `rustc --version`

**Comment by pventuzelo** [comment]
Hum, strange.

Here is my code:
``` rust
use wain_syntax_binary::parse;

use std::env;
use std::fs::File;
use std::io;
use std::io::Read;

/// Read the contents from file path
fn read_contents_from_path(path_str: &String) -> Result<Vec<u8>, io::Error> {
    let mut buffer: Vec<u8> = Vec::new();
    let file_path = std::path::PathBuf::from(path_str);

    println!("file_to_process: {:?}", file_path);

    let mut file = File::open(file_path)?;
    file.read_to_end(&mut buffer)?;
    drop(file);
    Ok(buffer)
}

fn main() {
    println!("Start debugging of wain_parser");
    let args: Vec<String> = env::args().collect();

    // verify file_to_process is provided
    if args.len() != 2 {
        println!("Usage: wain_parser <file_to_process>\n");
        return;
    }

    // read data from provided file
    let data = read_contents_from_path(&args[1]).expect("cannot read file content");

    // call the fuzzing target
    let _tree = match parse(&data) {
        Ok(_tree) => true,
        Err(_err) => false,
    };

    println!("No crash, everything is OK\n");
}
```

Cargo.toml:
``` toml
[dependencies]
wain-syntax-binary = "0.1.2"
```

Rustc:
``` sh 
$ rustc --version
rustc 1.44.0 (49cae5576 2020-06-01)
```

**Comment by rhysd** [comment]
Ah, ok, I uderstood. You're using released version. And current released version is a bit older than master branch of this repository.

I'll create a new release. Wait a minute.

**Comment by rhysd** [comment]
I have released wain-syntax-binary v0.1.3. Please use it.

**Comment by pventuzelo** [comment]
Perfect, thanks ;)

**Comment by pventuzelo** [comment]
I still trigger this crash but with another file this time.
file: [crash_wain_unwrap.zip](https://github.com/rhysd/wain/files/4765526/crash_wain_unwrap.zip)

**Comment by rhysd** [comment]
@pventuzelo Would you make another issue? Since this issue is already closed.

**Comment by pventuzelo** [comment]
Sure ;) Done
