### ISSUE TITLE
Way to Generate WAT from WASM?

### ISSUE THREAD

**Issue by zicklag** [rhysd/wain#55]
Hey there, I'm trying out this library and I was wondering whether or not there is a way to go from AST -> WAT so that I can convert from WASM -> AST -> WAT. Is this possible now or else simple to implement?

**Comment by rhysd** [comment]
Wain only has parser. Any code generator is not included because WebAssembly interpreter never needs a generator. If you want to convert wasm to wat, https://github.com/WebAssembly/wabt would be useful.
